// Единая точка входа. DOM, конфигурация, доступность, GSAP и офлайн-статус.
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Configurator } from './configurator.js';
import { EngineAudio } from './audio.js';
import { paints,interiors,comparison,sources,dataDisclaimer,gallery,calculateFuel } from './data.js';
const $=id=>document.getElementById(id);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
function stored(key){try{return localStorage.getItem(key)}catch{return null}}
function store(key,value){try{localStorage.setItem(key,value)}catch{/* Приватный режим: сайт продолжает работать. */}}
const params=new URLSearchParams(location.search);
const state={paint:paints.find(p=>p.id===(params.get('paint')||stored('v-paint')))||paints[0],interior:interiors.find(p=>p.id===(params.get('interior')||stored('v-interior')))||interiors[0]};
let configurator;
function select(type,item){state[type]=item;store('v-'+type,item.id);document.querySelectorAll(`[data-${type}]`).forEach(b=>b.setAttribute('aria-pressed',String(b.dataset[type]===item.id)));
 if(type==='paint'){$('paint-name').textContent=item.name;$('paint-code').textContent=item.finish;configurator?.setPaint(item.hex);}else{$('interior-name').textContent=item.name;$('leather-preview').style.backgroundColor=item.hex;configurator?.setInterior(item.hex);}}
function swatches(type,items,container){for(const item of items){const button=document.createElement('button');button.className='swatch';button.dataset[type]=item.id;button.style.setProperty('--swatch',item.hex);button.title=item.name;button.setAttribute('aria-label',item.name);button.setAttribute('aria-pressed',String(state[type].id===item.id));button.innerHTML='<span aria-hidden="true"></span>';button.addEventListener('click',()=>select(type,item));container.append(button);}}
swatches('paint',paints,$('paint-swatches'));swatches('interior',interiors,$('interior-swatches'));select('paint',state.paint);select('interior',state.interior);
// Готовность студии не блокирует остальные функции сайта.
function boot3D(){configurator?.dispose();$('viewer-loading').hidden=false;$('viewer-fallback').hidden=true;configurator=new Configurator($('viewer'),{paint:state.paint.hex,interior:state.interior.hex,onReady:()=>{$('viewer-loading').hidden=true;document.documentElement.dataset.modelReady='true';},onError:()=>{$('viewer-loading').hidden=true;$('viewer-fallback').hidden=false;document.documentElement.dataset.modelReady='false';$('rotation-label').textContent='3D НЕДОСТУПНО';},onRotation:active=>{$('rotation-label').textContent=active?'АВТОВРАЩЕНИЕ · 360°':'ПОТЯНИТЕ, ЧТОБЫ ВРАЩАТЬ';$('rotation-toggle').setAttribute('aria-pressed',String(active));}});configurator.init();}
boot3D();$('retry-3d').addEventListener('click',boot3D);
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>configurator.setView(button.dataset.view)));
$('show-interior').addEventListener('click',()=>{configurator.setView('interior');$('studio').scrollIntoView({behavior:reduced?'instant':'smooth',block:'center'});});
$('rotation-toggle').addEventListener('click',()=>{if(!configurator.ready)return;const active=configurator.toggleRotation();$('rotation-toggle').setAttribute('aria-pressed',String(active));toast(active?'Автовращение включено':'Автовращение приостановлено');});
// На клавиатуре также можно рассмотреть автомобиль.
$('viewer').addEventListener('keydown',e=>{if(!configurator.ready)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();configurator.interact();const c=configurator.camera,t=configurator.controls.target;const offset=c.position.clone().sub(t);if(e.key==='ArrowLeft'||e.key==='ArrowRight')offset.applyAxisAngle({x:0,y:1,z:0},e.key==='ArrowLeft'?.1:-.1);else offset.multiplyScalar(e.key==='+'||e.key==='ArrowUp'?.93:1.07);const distance=Math.max(3,Math.min(14,offset.length()));offset.setLength(distance);c.position.copy(t).add(offset);}});
function themeLabel(){const isLight=document.documentElement.dataset.theme==='light';$('theme-toggle').setAttribute('aria-label',isLight?'Включить тёмную тему':'Включить светлую тему');document.querySelector('meta[name="theme-color"]').content=isLight?'#f0f1f3':'#1a1a2e';}
themeLabel();$('theme-toggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'dark':'light';store('v-theme',document.documentElement.dataset.theme);themeLabel();configurator.applyTheme();});
async function share(){const url=new URL(location.href);url.searchParams.set('paint',state.paint.id);url.searchParams.set('interior',state.interior.id);url.hash='studio';try{await navigator.clipboard.writeText(url.href);toast('Ссылка на вашу конфигурацию скопирована');}catch{const input=document.createElement('textarea');input.value=url.href;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const copied=document.execCommand('copy');input.remove();if(copied)toast('Ссылка на вашу конфигурацию скопирована');else{history.replaceState(null,'',url);toast('Конфигурация в адресной строке — скопируйте ссылку');}}}
$('share').addEventListener('click',share);$('share-bottom').addEventListener('click',share);
// Данные — только из локального модуля, не из небезопасного HTML пользователя.
for(const row of comparison){const tr=document.createElement('tr');const label=document.createElement('th');label.scope='row';label.textContent=row.label;tr.append(label);for(const value of row.values){const td=document.createElement('td');const span=document.createElement('span');span.textContent=value;if(row.em)span.className='value-em';td.append(span);tr.append(td);}$('comparison-body').append(tr);}
for(const source of sources){const p=document.createElement('p');const a=document.createElement('a');a.href=source.url;a.target='_blank';a.rel='noopener';a.textContent=source.label+' ↗';p.append(a,document.createTextNode(' — '+source.note));$('source-notes').append(p);}const note=document.createElement('p');note.textContent=dataDisclaimer;$('source-notes').append(note);
const engine=new EngineAudio();for(let i=0;i<44;i++){const bar=document.createElement('i');bar.style.setProperty('--h',`${5+Math.sin(i*.67)**2*23}px`);bar.style.setProperty('--delay',`${-i*.13}s`);document.querySelector('.equalizer').append(bar);}
function audioUI(){const on=engine.running;$('engine-label').textContent=on?'Заглушить двигатель':'Завести двигатель';$('engine-start').setAttribute('aria-pressed',String(on));$('sound-status').textContent=on?'V8 / RUNNING':'OFF';$('rev').disabled=!on;$('exhaust').disabled=!on;document.querySelector('.sound-panel').classList.toggle('running',on);}
let starting=false;$('engine-start').addEventListener('click',async()=>{if(starting)return;starting=true;try{if(engine.running)engine.stop();else{await engine.start();configurator.shake(.025,1.3);}audioUI();}catch{toast('Браузер не смог запустить звук. Проверьте поддержку Web Audio.');}finally{starting=false;}});
$('rev').addEventListener('click',()=>{if(engine.rev())configurator.shake(.04,1.6);});$('exhaust').addEventListener('click',()=>{if(engine.exhaust())configurator.shake(.024,1.1);});
$('volume').addEventListener('input',e=>{engine.setVolume(Number(e.target.value)/100);$('volume-value').textContent=e.target.value+'%';});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&engine.running){engine.stop();audioUI();}});
window.addEventListener('pagehide',()=>engine.stop());
let galleryIndex=0,credits=[];
function showPhoto(index){galleryIndex=(index+gallery.length)%gallery.length;const item=gallery[galleryIndex];$('gallery-image').src=new URL('../assets/images/'+item.file,import.meta.url).href;$('gallery-image').alt=item.alt;$('gallery-title').textContent=item.title;$('gallery-description').textContent=item.description;$('gallery-count').textContent=String(galleryIndex+1).padStart(2,'0')+' / 03';const credit=credits.find(c=>c.file===item.file);if(credit){$('gallery-credit').href=credit.url;$('gallery-credit').textContent=`${credit.author} · ${credit.license} ↗`;}}
fetch(new URL('../assets/images/credits.json',import.meta.url)).then(r=>r.json()).then(data=>{credits=data;showPhoto(galleryIndex)}).catch(()=>{/* Атрибуция также доступна в SOURCES.md. */});
$('gallery-prev').addEventListener('click',()=>showPhoto(galleryIndex-1));$('gallery-next').addEventListener('click',()=>showPhoto(galleryIndex+1));let touchX;const galleryElement=document.querySelector('.gallery');galleryElement.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].screenX;},{passive:true});galleryElement.addEventListener('touchend',e=>{const delta=e.changedTouches[0].screenX-touchX;if(Math.abs(delta)>60)showPhoto(galleryIndex+(delta<0?1:-1));},{passive:true});
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function updateFuel(){const km=Number($('annual-distance').value),price=Number($('fuel-price').value),city=Number($('city-share').value);$('city-share-value').textContent=city+'%';if(!$('fuel-form').checkValidity()||!Number.isFinite(km)||!Number.isFinite(price)){$('fuel-total').textContent='—';$('fuel-details').textContent='Введите корректные неотрицательные значения';return;}const highway=$('efficiency-profile').value==='brief'?17:16;const result=calculateFuel(km,price,city,highway);$('fuel-total').textContent=money.format(result.cost);$('fuel-details').textContent=`${Math.round(result.litres).toLocaleString('ru-RU')} л / год · ${result.l100.toFixed(1)} л / 100 км`;$('fuel-form').querySelector('.formula-note').textContent=`Взвешенный расход = город × 235,215/11 + трасса × 235,215/${highway} л/100 км. Не среднее арифметическое mpg.`;}
$('fuel-form').addEventListener('submit',e=>e.preventDefault());$('fuel-form').addEventListener('input',updateFuel);$('fuel-form').addEventListener('change',updateFuel);updateFuel();
if(!reduced){gsap.registerPlugin(ScrollTrigger);gsap.from('.hero-copy',{y:24,opacity:0,duration:1.1,ease:'power3.out'});gsap.from('.hero-top',{opacity:0,duration:1,delay:.2});gsap.utils.toArray('.reveal').forEach(el=>{gsap.from(el,{y:25,opacity:0,duration:.85,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 94%',once:true}});});
 if(matchMedia('(pointer:fine)').matches){const dot=document.querySelector('.cursor-dot'),trail=document.querySelector('.cursor-trail');const xTo=gsap.quickTo(trail,'x',{duration:.35,ease:'power3'}),yTo=gsap.quickTo(trail,'y',{duration:.35,ease:'power3'});window.addEventListener('pointermove',e=>{dot.style.opacity='1';trail.style.opacity='1';gsap.set(dot,{x:e.clientX-2,y:e.clientY-2});xTo(e.clientX-12);yTo(e.clientY-12);});document.addEventListener('pointerleave',()=>{dot.style.opacity='0';trail.style.opacity='0';});}}
// Все зависимости в локальной сборке — CDN не нужен даже при первом визите.
if('serviceWorker' in navigator){navigator.serviceWorker.register(new URL('../sw.js',import.meta.url),{scope:new URL('../',import.meta.url).pathname}).then(async registration=>{await navigator.serviceWorker.ready;const worker=registration.active||navigator.serviceWorker.controller;worker?.postMessage({type:'STATUS'});}).catch(()=>{$('offline-state').textContent='ОФЛАЙН-КЭШ НЕДОСТУПЕН';});navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='CACHE_READY')$('offline-state').textContent='OFFLINE-READY / ВСЁ СОХРАНЕНО НА УСТРОЙСТВЕ';});}else $('offline-state').textContent='SERVICE WORKER НЕ ПОДДЕРЖИВАЕТСЯ';
