// Сборка без CDN. Бинарные материалы хранятся в текстовом транспортном формате.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {gunzipSync} from 'node:zlib';import {build} from 'esbuild';
const root=process.cwd();fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/js',{recursive:true});
for(const file of ['index.html','css','assets','SOURCES.md','README.md']){if(fs.existsSync(file))fs.cpSync(file,path.join('dist',file),{recursive:true,filter:p=>!p.endsWith('.b64')&&!p.endsWith('.gltf')});}
function decode(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())decode(p);else if(p.endsWith('.b64')){let bytes=Buffer.from(fs.readFileSync(p,'utf8'),'base64');const name=p.slice(0,-4).replace(/\.gz$/,'');if(p.endsWith('.gz.b64'))bytes=gunzipSync(bytes);const dest=path.join('dist',name);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,bytes);}}}
decode('assets');await build({entryPoints:['js/app.js'],bundle:true,minify:true,format:'esm',target:['es2022'],outfile:'dist/js/app.js',legalComments:'eof'});
fs.copyFileSync('LICENSE','dist/LICENSE');
let files=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else files.push('./'+p.slice(5).replaceAll(path.sep,'/'));}}walk('dist');
const hash=crypto.createHash('sha256');for(const f of files)hash.update(fs.readFileSync(path.join('dist',f)));const version=hash.digest('hex').slice(0,12);
const sw=`// Сгенерировано scripts/build.mjs. Scope-safe для GitHub Pages project path.\nconst CACHE='v-studio-${version}';const FILES=${JSON.stringify(files)};const scope=self.registration.scope;\nself.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES.map(f=>new URL(f,scope).href))).then(()=>self.skipWaiting()));});\nself.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('v-studio-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()).then(()=>self.clients.matchAll()).then(clients=>clients.forEach(client=>client.postMessage({type:'CACHE_READY'}))));});\nself.addEventListener('message',event=>{if(event.data?.type==='STATUS')event.waitUntil(caches.has(CACHE).then(ready=>{if(ready)event.source?.postMessage({type:'CACHE_READY'});}));});\nself.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(event.request.method!=='GET'||!u.href.startsWith(scope))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);if(event.request.mode==='navigate'){try{const r=await fetch(event.request);if(r.ok)return r;}catch{}return (await cache.match(new URL('./index.html',scope).href))||Response.error();}u.search='';return (await cache.match(u.href))||fetch(event.request);})());});\n`;
fs.writeFileSync('dist/sw.js',sw);fs.writeFileSync('dist/.nojekyll','');console.log('Built dist:',files.length,'cached files; cache version',version);
